<?php
	
	require_once('fpdf.php');
	
	class pdf extends FPDF
	{
		function Header()
		{
			parent::Header(); // TODO: Change the autogenerated stub
			
			$this->Image('images/background_logo.jpg', 10, 6, 190);
			$this->SetFont('Arial', 'B', 15);
			$this->Cell(70);
			$this->Cell(30, 110, 'Your reservation');
			$this->Ln(70);
		}
		
		
		
		function Footer()
		{
			parent::Footer(); // TODO: Change the autogenerated stub
			
			$this->SetY(-15);
			$this->SetFont('Arial', 'I', 8);
			$this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
		}
	}

?>